### PR TITLE
Updating deps with security issues

### PR DESCRIPTION
**Pull request by LindsayHill**
As above. We're not using this repo anymore, but this will get rid of the GH notifications.

### CODE REVIEW

**Comment by arm4b** [comment]
Chef itself is used by the community, though not that popular as Ansible which we take care of and Puppet which Nick takes care of.

I'll look into fixing the build failure + merging this.

**Comment by arm4b** [comment]
In fact, the PR is the same as https://github.com/StackStorm/chef-openstack-mistral/pull/7

**Comment by LindsayHill** [comment]
> Chef itself is used by the community,
True, but this particular repo is not used anymore - it pre-dates RPMs/Debs for st2mistral.

Closed this in favor of #7.

I think we should just delete the whole repo though.

**Comment by arm4b** [comment]
> True, but this particular repo is not used anymore - it pre-dates RPMs/Debs for st2mistral.

Not really, it installs `st2mistral` deb/rpm, installs & configures PostgreSQL server, handles `mistral.conf` settings including DB and ensures running the mistral DB migration.

So at a high level it's not different to what we do in Ansible or Puppet repos. This to be consumed by the community.

**Comment by LindsayHill** [comment]
Ah right, sorry, I misread the README. 

Last commit to this repo was 2yrs ago. I don't think anyone in the community is consuming it. No-one seems to care about the issues, or security alerts. So fix up the build failures if you like, but it doesn't feel like it's worth putting much effort into this.

**Pull request closed without merging**
